/**
 * Online Assessment (OA / Aptitude) — MCQ Question Bank
 *
 * 60 questions across 4 categories:
 *  1) Quantitative Aptitude     (oa-quant-1  … oa-quant-20)   → 20 questions
 *  2) Logical Reasoning         (oa-logical-21 … oa-logical-40) → 20 questions
 *  3) Verbal Ability            (oa-verbal-41 … oa-verbal-55)  → 15 questions
 *  4) Non-Verbal Reasoning      (oa-nonverbal-56 … oa-nonverbal-60) → 5 questions
 *
 * Per-session selection (see getAptitudeQuestions in questions.ts):
 *   7  Quantitative  +  7  Logical Reasoning  +  4  Verbal Ability  +  2  Non-Verbal  =  20 total
 *
 * Fields:
 *   options  – four answer choices (index 0-3 → A-D)
 *   answer   – correct option letter ("A" | "B" | "C" | "D")
 */

import type { OAQuestion } from "./question-types";

export const OA_QUESTIONS: OAQuestion[] = [
  // ──────────────────────────────────────────────────────────────────────────
  // 1) Quantitative Aptitude  (oa-quant-1 … oa-quant-20)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "oa-quant-1",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A shopkeeper buys an article for ₹800 and marks it 25% above cost price. He gives successive discounts of 10% and 5%. What is the selling price?",
    options: ["₹840", "₹855", "₹860", "₹875"],
    answer: "B",
    answerKeywords: ["₹855"],
    expectedAnswer: "₹855",
  },
  {
    id: "oa-quant-2",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "The average of 9 numbers is 42. If one number 36 is replaced by 54, the new average is:",
    options: ["43", "44", "45", "46"],
    answer: "B",
    answerKeywords: ["44"],
    expectedAnswer: "44",
  },
  {
    id: "oa-quant-3",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A can complete a work in 18 days and B in 24 days. They work together for 6 days, after which A leaves. B finishes the remaining work alone. Total time taken is:",
    options: ["14 days", "15 days", "16 days", "17 days"],
    answer: "C",
    answerKeywords: ["16 days"],
    expectedAnswer: "16 days",
  },
  {
    id: "oa-quant-4",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "Pipe A fills a tank in 12 hours, Pipe B fills it in 18 hours, and a leak empties it in 36 hours. If all are open together, the tank will be filled in:",
    options: ["8 hours", "9 hours", "10 hours", "12 hours"],
    answer: "B",
    answerKeywords: ["9 hours"],
    expectedAnswer: "9 hours",
  },
  {
    id: "oa-quant-5",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A boat covers 24 km downstream in 3 hours and the same distance upstream in 6 hours. The speed of the stream is:",
    options: ["1 km/h", "2 km/h", "3 km/h", "4 km/h"],
    answer: "B",
    answerKeywords: ["2 km/h"],
    expectedAnswer: "2 km/h",
  },
  {
    id: "oa-quant-6",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "In a 60-litre mixture, milk and water are in the ratio 2:1. How much water should be added so that the ratio becomes 2:3?",
    options: ["20 litres", "30 litres", "40 litres", "50 litres"],
    answer: "C",
    answerKeywords: ["40 litres"],
    expectedAnswer: "40 litres",
  },
  {
    id: "oa-quant-7",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question: "If 40% of a number is 96, then 75% of the same number is:",
    options: ["160", "170", "180", "190"],
    answer: "C",
    answerKeywords: ["180"],
    expectedAnswer: "180",
  },
  {
    id: "oa-quant-8",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A sum of ₹10,000 is invested at 10% compound interest per annum. The amount after 2 years is:",
    options: ["₹12,000", "₹12,100", "₹12,200", "₹12,300"],
    answer: "B",
    answerKeywords: ["₹12,100"],
    expectedAnswer: "₹12,100",
  },
  {
    id: "oa-quant-9",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "The HCF of two numbers is 12 and their LCM is 720. If one number is 72, the other number is:",
    options: ["100", "108", "120", "144"],
    answer: "C",
    answerKeywords: ["120"],
    expectedAnswer: "120",
  },
  {
    id: "oa-quant-10",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question: "A train 180 m long passes a pole in 9 seconds. Its speed is:",
    options: ["60 km/h", "72 km/h", "75 km/h", "80 km/h"],
    answer: "B",
    answerKeywords: ["72 km/h"],
    expectedAnswer: "72 km/h",
  },
  {
    id: "oa-quant-11",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "The ages of A and B are in the ratio 5:7. After 6 years, their ages are in the ratio 3:4. A's present age is:",
    options: ["25 years", "28 years", "30 years", "35 years"],
    answer: "C",
    answerKeywords: ["30 years"],
    expectedAnswer: "30 years",
  },
  {
    id: "oa-quant-12",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "Find the smallest positive number that leaves remainder 3 when divided by 5 and remainder 4 when divided by 7.",
    options: ["13", "18", "23", "28"],
    answer: "B",
    answerKeywords: ["18"],
    expectedAnswer: "18",
  },
  {
    id: "oa-quant-13",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A number is increased by 20% and then decreased by 20%. The net change is:",
    options: ["0%", "2% increase", "4% decrease", "4% increase"],
    answer: "C",
    answerKeywords: ["4% decrease"],
    expectedAnswer: "4% decrease",
  },
  {
    id: "oa-quant-14",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question: "If 3x − 2 = 4x + 7, then x =",
    options: ["−7", "−8", "−9", "9"],
    answer: "C",
    answerKeywords: ["−9"],
    expectedAnswer: "−9",
  },
  {
    id: "oa-quant-15",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "How many 4-digit numbers can be formed using digits 1, 2, 3, 4, 5 without repetition and ending in 5?",
    options: ["12", "18", "24", "36"],
    answer: "C",
    answerKeywords: ["24"],
    expectedAnswer: "24",
  },
  {
    id: "oa-quant-16",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question: "The sum of the first 30 natural numbers is:",
    options: ["450", "465", "480", "495"],
    answer: "B",
    answerKeywords: ["465"],
    expectedAnswer: "465",
  },
  {
    id: "oa-quant-17",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A product costs ₹800. It is marked 20% above cost price and sold at 10% discount. The profit is:",
    options: ["₹48", "₹64", "₹72", "₹80"],
    answer: "B",
    answerKeywords: ["₹64"],
    expectedAnswer: "₹64",
  },
  {
    id: "oa-quant-18",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A car covers 240 km. If its speed is increased by 20 km/h, the journey takes 1 hour less. The original speed is:",
    options: ["40 km/h", "50 km/h", "60 km/h", "70 km/h"],
    answer: "C",
    answerKeywords: ["60 km/h"],
    expectedAnswer: "60 km/h",
  },
  {
    id: "oa-quant-19",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "If 8 men or 12 women can complete a work in 15 days, then 4 men and 6 women together can complete it in:",
    options: ["10 days", "12 days", "15 days", "18 days"],
    answer: "C",
    answerKeywords: ["15 days"],
    expectedAnswer: "15 days",
  },
  {
    id: "oa-quant-20",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Quantitative",
    question:
      "A and B can complete a work in 10 days and 15 days respectively. If they work on alternate days starting with A, the work will be completed in:",
    options: ["5 days", "6 days", "7 days", "8 days"],
    answer: "B",
    answerKeywords: ["6 days"],
    expectedAnswer: "6 days",
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 2) Logical Reasoning  (oa-logical-21 … oa-logical-40)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "oa-logical-21",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "Five friends A, B, C, D, E sit in a row facing north. B is between A and C. D is immediately right of E. A is at one end and C is not at the extreme right. Who sits in the middle?",
    options: ["A", "B", "C", "D"],
    answer: "C",
    answerKeywords: ["C"],
    expectedAnswer: "C",
  },
  {
    id: "oa-logical-22",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "Six people A, B, C, D, E, F sit around a circle facing the center. A is opposite C. B is immediate left of A. D is immediate right of C. E is opposite B. Who is immediate left of D?",
    options: ["A", "B", "C", "F"],
    answer: "C",
    answerKeywords: ["C"],
    expectedAnswer: "C",
  },
  {
    id: "oa-logical-23",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "A person walks 12 m north, then 5 m east, then 7 m south, then 3 m west. How far is he from the starting point?",
    options: ["√20 m", "√25 m", "√29 m", "√34 m"],
    answer: "C",
    answerKeywords: ["√29 m"],
    expectedAnswer: "√29 m",
  },
  {
    id: "oa-logical-24",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      'Pointing to a boy, Nita said, "He is the son of my father\'s only daughter." How is the boy related to Nita?',
    options: ["Brother", "Son", "Nephew", "Cousin"],
    answer: "B",
    answerKeywords: ["Son"],
    expectedAnswer: "Son",
  },
  {
    id: "oa-logical-25",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Thermometer : Temperature :: Barometer : ?",
    options: ["Speed", "Pressure", "Humidity", "Weight"],
    answer: "B",
    answerKeywords: ["Pressure"],
    expectedAnswer: "Pressure",
  },
  {
    id: "oa-logical-26",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Find the odd one out.",
    options: ["Cube", "Cuboid", "Sphere", "Cylinder"],
    answer: "C",
    answerKeywords: ["Sphere"],
    expectedAnswer: "Sphere",
  },
  {
    id: "oa-logical-27",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Find the next term in the series: 3, 8, 18, 38, 78, ?",
    options: ["148", "156", "158", "160"],
    answer: "C",
    answerKeywords: ["158"],
    expectedAnswer: "158",
  },
  {
    id: "oa-logical-28",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Find the next letter in the series: B, E, J, Q, Z, ?",
    options: ["H", "K", "L", "M"],
    answer: "B",
    answerKeywords: ["K"],
    expectedAnswer: "K",
  },
  {
    id: "oa-logical-29",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: 'In a certain code, TABLE is written as UBCMF. How is CHAIR written?',
    options: ["DIBJS", "DHCIR", "EJCJS", "DIBKT"],
    answer: "A",
    answerKeywords: ["DIBJS"],
    expectedAnswer: "DIBJS",
  },
  {
    id: "oa-logical-30",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "If CAT = 24 and DOG = 26, then HEN = ?",
    options: ["25", "26", "27", "28"],
    answer: "C",
    answerKeywords: ["27"],
    expectedAnswer: "27",
  },
  {
    id: "oa-logical-31",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "Statements: All roses are flowers. Some flowers are red. No red is blue.\nConclusions:\nI. Some flowers are not blue.\nII. Some roses may be red.",
    options: [
      "Only I follows",
      "Only II follows",
      "Both follow",
      "Neither follows",
    ],
    answer: "A",
    answerKeywords: ["Only I follows"],
    expectedAnswer: "Only I follows",
  },
  {
    id: "oa-logical-32",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "Statements: Some pens are pencils. All pencils are erasers. No eraser is rubber.\nConclusions:\nI. Some pens are erasers.\nII. Some pens are not rubber.",
    options: [
      "Only I follows",
      "Only II follows",
      "Both follow",
      "Neither follows",
    ],
    answer: "C",
    answerKeywords: ["Both follow"],
    expectedAnswer: "Both follow",
  },
  {
    id: "oa-logical-33",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "Statement: Only if it rains will the match be postponed. The match was postponed. Conclusion:",
    options: [
      "It did not rain",
      "It rained",
      "The match was cancelled",
      "The ground was dry",
    ],
    answer: "B",
    answerKeywords: ["It rained"],
    expectedAnswer: "It rained",
  },
  {
    id: "oa-logical-34",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "In a class of 40 students, Rohan is 12th from the top. His rank from the bottom is:",
    options: ["27th", "28th", "29th", "30th"],
    answer: "C",
    answerKeywords: ["29th"],
    expectedAnswer: "29th",
  },
  {
    id: "oa-logical-35",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      "A father is twice as old as his son. After 10 years, he will be 1.5 times as old as his son. The son's present age is:",
    options: ["8 years", "10 years", "12 years", "14 years"],
    answer: "B",
    answerKeywords: ["10 years"],
    expectedAnswer: "10 years",
  },
  {
    id: "oa-logical-36",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Statements: X > Y ≥ Z = W. Which conclusion follows?",
    options: ["X > W", "Y > W", "Z > X", "W > X"],
    answer: "A",
    answerKeywords: ["X > W"],
    expectedAnswer: "X > W",
  },
  {
    id: "oa-logical-37",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Find the next term: 4, 9, 19, 39, 79, ?",
    options: ["149", "157", "159", "161"],
    answer: "C",
    answerKeywords: ["159"],
    expectedAnswer: "159",
  },
  {
    id: "oa-logical-38",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: "Find the next term: 1, 2, 6, 24, 120, ?",
    options: ["240", "360", "720", "840"],
    answer: "C",
    answerKeywords: ["720"],
    expectedAnswer: "720",
  },
  {
    id: "oa-logical-39",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question: 'In a certain code, "MANGO" is written as "NZOHP". How is "APPLE" written?',
    options: ["BQPMF", "BQQMF", "CQQMF", "BQRMF"],
    answer: "B",
    answerKeywords: ["BQQMF"],
    expectedAnswer: "BQQMF",
  },
  {
    id: "oa-logical-40",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Logical Reasoning",
    question:
      'Which option strengthens the statement: "Remote work reduces company expenses"?',
    options: [
      "Employees spend more time commuting",
      "Remote work requires office space",
      "Remote workers use fewer office resources",
      "Meetings become longer",
    ],
    answer: "C",
    answerKeywords: ["Remote workers use fewer office resources"],
    expectedAnswer: "Remote workers use fewer office resources",
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 3) Verbal Ability  (oa-verbal-41 … oa-verbal-55)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "oa-verbal-41",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Synonym of pervasive is:",
    options: ["Rare", "Widespread", "Weak", "Temporary"],
    answer: "B",
    answerKeywords: ["Widespread"],
    expectedAnswer: "Widespread",
  },
  {
    id: "oa-verbal-42",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Antonym of mitigate is:",
    options: ["Reduce", "Aggravate", "Ease", "Lessen"],
    answer: "B",
    answerKeywords: ["Aggravate"],
    expectedAnswer: "Aggravate",
  },
  {
    id: "oa-verbal-43",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Fill in the blank: The team adhered ___ the original plan.",
    options: ["on", "to", "with", "at"],
    answer: "B",
    answerKeywords: ["to"],
    expectedAnswer: "to",
  },
  {
    id: "oa-verbal-44",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question:
      'Spot the error: "Each of the candidates have submitted their documents."',
    options: ["Each", "have", "submitted", "documents"],
    answer: "B",
    answerKeywords: ["have"],
    expectedAnswer: "have",
  },
  {
    id: "oa-verbal-45",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Choose the correct sentence:",
    options: [
      "He did not knew the answer.",
      "He did not know the answer.",
      "He do not know the answer.",
      "He not knew the answer.",
    ],
    answer: "B",
    answerKeywords: ["He did not know the answer."],
    expectedAnswer: "He did not know the answer.",
  },
  {
    id: "oa-verbal-46",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "The idiom 'on cloud nine' means:",
    options: ["Confused", "Angry", "Extremely happy", "Very tired"],
    answer: "C",
    answerKeywords: ["Extremely happy"],
    expectedAnswer: "Extremely happy",
  },
  {
    id: "oa-verbal-47",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "One-word substitution for a person who studies coins is:",
    options: ["Philatelist", "Numismatist", "Linguist", "Botanist"],
    answer: "B",
    answerKeywords: ["Numismatist"],
    expectedAnswer: "Numismatist",
  },
  {
    id: "oa-verbal-48",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Synonym of concise is:",
    options: ["Brief", "Complex", "Loud", "Vague"],
    answer: "A",
    answerKeywords: ["Brief"],
    expectedAnswer: "Brief",
  },
  {
    id: "oa-verbal-49",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Antonym of hostile is:",
    options: ["Aggressive", "Friendly", "Angry", "Fierce"],
    answer: "B",
    answerKeywords: ["Friendly"],
    expectedAnswer: "Friendly",
  },
  {
    id: "oa-verbal-50",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Synonym of ubiquitous is:",
    options: ["Rare", "Present everywhere", "Weak", "Hidden"],
    answer: "B",
    answerKeywords: ["Present everywhere"],
    expectedAnswer: "Present everywhere",
  },
  {
    id: "oa-verbal-51",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Synonym of prudent is:",
    options: ["Careless", "Cautious", "Reckless", "Lazy"],
    answer: "B",
    answerKeywords: ["Cautious"],
    expectedAnswer: "Cautious",
  },
  {
    id: "oa-verbal-52",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Fill in the blank: She is fond ___ classical music.",
    options: ["at", "of", "for", "on"],
    answer: "B",
    answerKeywords: ["of"],
    expectedAnswer: "of",
  },
  {
    id: "oa-verbal-53",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Choose the correct sentence:",
    options: [
      "Scarcely I had reached the station when the train left.",
      "Scarcely had I reached the station when the train left.",
      "Scarcely had I reach the station when the train left.",
      "Scarcely had I reached station when train left.",
    ],
    answer: "B",
    answerKeywords: ["Scarcely had I reached the station when the train left."],
    expectedAnswer: "Scarcely had I reached the station when the train left.",
  },
  {
    id: "oa-verbal-54",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Synonym of astute is:",
    options: ["Shrewd", "Dull", "Simple", "Carefree"],
    answer: "A",
    answerKeywords: ["Shrewd"],
    expectedAnswer: "Shrewd",
  },
  {
    id: "oa-verbal-55",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Verbal Ability",
    question: "Antonym of archaic is:",
    options: ["Ancient", "Old-fashioned", "Modern", "Primitive"],
    answer: "C",
    answerKeywords: ["Modern"],
    expectedAnswer: "Modern",
  },

  // ──────────────────────────────────────────────────────────────────────────
  // 4) Non-Verbal Reasoning  (oa-nonverbal-56 … oa-nonverbal-60)
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "oa-nonverbal-56",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Non-Verbal Reasoning",
    question:
      "A cube is painted on all faces and cut into 125 equal small cubes. How many small cubes have paint on exactly 3 faces?",
    options: ["6", "8", "12", "24"],
    answer: "B",
    answerKeywords: ["8"],
    expectedAnswer: "8",
  },
  {
    id: "oa-nonverbal-57",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Non-Verbal Reasoning",
    question:
      "A cube is painted on all faces and cut into 64 equal small cubes. How many small cubes have paint on exactly 1 face?",
    options: ["12", "18", "24", "36"],
    answer: "C",
    answerKeywords: ["24"],
    expectedAnswer: "24",
  },
  {
    id: "oa-nonverbal-58",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Non-Verbal Reasoning",
    question:
      "A cube is painted on two opposite faces only and cut into 27 equal small cubes. How many small cubes have exactly one painted face?",
    options: ["9", "12", "18", "24"],
    answer: "C",
    answerKeywords: ["18"],
    expectedAnswer: "18",
  },
  {
    id: "oa-nonverbal-59",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Non-Verbal Reasoning",
    question:
      "A square paper is folded twice and a hole is punched at the corner of the folded paper. After unfolding, how many holes will there be?",
    options: ["2", "3", "4", "8"],
    answer: "C",
    answerKeywords: ["4"],
    expectedAnswer: "4",
  },
  {
    id: "oa-nonverbal-60",
    role: "online-assessment",
    roundType: "online-assessment",
    topic: "Non-Verbal Reasoning",
    question: "What is the angle between the hands of a clock at 4:20?",
    options: ["5°", "10°", "15°", "20°"],
    answer: "B",
    answerKeywords: ["10°"],
    expectedAnswer: "10°",
  },
];
